routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'PostController@index')->name('home');
Route::resource('post','PostController');
Route::resource('profile','ProfileController');
Route::resource('likepost','LikePostController')->only([
    'store','destroy'
]);
Route::resource('likecomment','LikeCommentController')->only([
    'store','destroy'
]);
Route::resource('post.comment','CommentController')->shallow();

Route::post('/follow','UserController@followUser')->name('follow');
Route::delete('/unfollow','UserController@unfollowUser')->name('unfollow');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $guarded = [];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function comment(){
        return $this->hasMany('App\postComments');
    }

    public function likes(){
        return $this->belongsToMany('App\User','post_likes','post_id','user_id');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\postComments;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Traits\storeImageTrait;

class PostController extends Controller
{
    use storeImageTrait;

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        //
        $posts = Post::all();
        return view('post.post',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request);
        //
        $request->validate([
            'judul' => 'required',
            'deskripsi' => 'required'
        ]);
        $user = Auth::user();
        $post = $user->post()->create([
            'judul' => $request['judul'],
            'deskripsi' => $request['deskripsi'],
            'image' => $this->storeImageToPath($request,'image','post_images'),
            'likes' => 0
        ]);

        return redirect('/post');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $post = Post::find($id);
        $comments = postComments::where('post_id',$id)->get();
        return view('post.show',compact('post','comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $post = Post::find($id);
        return view('post.edit',compact('post'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'judul' => 'required',
            'deskripsi' => 'required'
        ]);

        if($request->hasFile('image')){
            $query = Post::where('id',$id)->update([
                'judul' => $request['judul'],
                'deskripsi' => $request['deskripsi'],
                'image' => $this->storeImageToPath($request,'image','post_images')
            ]);
        }
        else{
            $query = Post::where('id',$id)->update([
                'judul' => $request['judul'],
                'deskripsi' => $request['deskripsi']
            ]);
        }

        return redirect('/post');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Post::destroy($id);
        return redirect('post');
    }
}

resources/views/post/create.blade.php
@extends('adminLTE.master')

@section('content')
    <div class="container">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <a class="btn btn-primary" href="{{route('post.index')}}">
                            <i class="fa fa-arrow-left"></i>
                            <span class="ml-2">Back</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    New Post
                </div>
                <form action="{{route('post.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="judulPost" class="col-sm-2 col-form-label">Judul</label>
                            <div class="col-sm-10">
                                @if($errors->has('judulPost'))
                                    <input type="text" class="form-control is-invalid" value="{{ old('judul','') }}" id="judulPost" name="judul" placeholder="Judul">
                                    <span class="invalid-feedback">This field cannot be empty</span>
                                @else
                                    <input type="text" class="form-control" id="judulPost" value="{{ old('judul','') }}" name="judul" placeholder="Judul">
                                @endif
                            </div>
                        </div>
                        <textarea class="form-control" rows="3" placeholder="What's on your mind?" id="deskripsi" name="deskripsi"></textarea>
                        <div class="form-group row mt-1">
                            <label for="post-image" class="col-md-1 col-form-label">{{ __('Image') }}</label>
                            <div class="col-md-6">
                                <input type="file" class="form-control-sm" id="post-image" name="image" value="{{old('image','')}}" placeholder="Enter Image">
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="container-fluid"><button type="submit" class="btn btn-primary float-right">
                                    {{ __('Post') }}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('adminLTE.master')

@section('content')
    <div class="container">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <a class="btn btn-primary" href="{{route('post.index')}}">
                            <i class="fa fa-arrow-left"></i>
                            <span class="ml-2">Back</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Edit Section
                </div>
                <form action="{{route('post.update',['post' => $post->id])}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="judulPost" class="col-sm-2 col-form-label">Judul</label>
                            <div class="col-sm-10">
                                @if($errors->has('judulPost'))
                                    <input type="text" class="form-control is-invalid" value="{{ old('judul',$post->judul) }}" id="judulPost" name="judul" placeholder="Judul">
                                    <span class="invalid-feedback">This field cannot be empty</span>
                                @else
                                    <input type="text" class="form-control" id="judulPost" value="{{ old('judul',$post->judul) }}" name="judul" placeholder="Judul">
                                @endif
                            </div>
                        </div>
                        <textarea class="form-control" rows="3" placeholder="What's on your mind?" id="deskripsi" name="deskripsi">{{ old('deskripsi',$post->deskripsi) }}</textarea>
                        <div class="form-group row mt-1">
                            <label for="profile_image" class="col-md-1 col-form-label">{{ __('Image') }}</label>
                            <div class="col-md-6">
                                <input type="file" class="form-control-sm" id="image" name="image" value="{{old('image',$post->image)}}" placeholder="Enter Image">
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="container-fluid"><button type="submit" class="btn btn-primary float-right">
                                    {{ __('Post') }}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/post/post.blade.php
@extends('adminLTE.master')

@section('content')
<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Posts</h1>
                </div>
                <div class="col-sm-6">
                    <a href="{{ route('post.create') }}" class="btn btn-primary float-sm-right">
                        <i class="fa fa-plus"></i>
                        <span class="border-left m-2 p-2">
                            Create Post
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12 py-2">
        @forelse($posts as $key => $post)
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-10">
                            <a href="{{route('post.show',['post' => $post->id])}}" class="h2">{{$post->judul}}</a>
                        </div>
                        <div class="col-sm-2">
                            @if($post->user->id == Auth::user()->id)
                                <div class="dropdown show float-right">
                                    <a class="" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-ellipsis-v text-secondary"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" href="{{route('post.edit',['post' => $post->id])}}">Edit</a>
                                        <form action="{{route('post.destroy',['post' => $post->id])}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <input type="submit" value="Delete" class="dropdown-item text-danger">
                                        </form>
                                    </div>
                                </div>
                            @endif
                        </div>
                    </div>
                    <hr>
                    @if($post->image != "noimage.jpg")
                        <div class="container-fluid d-flex justify-content-center">
                            <img src="{{asset('storage/post_images/' . $post->image)}}" style="max-width: 500px; max-height: 500px; object-fit: cover">
                        </div>
                    @endif
                    <p>{{$post->deskripsi}}</p>
                </div>
                <div class="card-footer py-1">
                    <div class="row" >
                        <div class="col-sm-10" style="border-radius: 5px 0px 0px 5px">
                            <div class="w-100">
                                <span style="font-size: 1.4em">
                                    @if($post->likes()->where('user_id',Auth::user()->id)->exists())
                                        <form action="{{route('likepost.destroy',['likepost' => $post->id])}}" method='post'>
                                        @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-link btn-lg">
                                                <i class="fa fa-heart"></i>
                                                <span class="ml-1">{{$post->likes}}</span>
                                            </button>
                                        </form>
                                    @else
                                        <form action="{{route('likepost.store')}}" method="POST">
                                        @csrf
                                            <input type="hidden" name="id" value="{{$post->id}}">
                                            <button type="submit" class="btn btn-link btn-lg">
                                                <i class="far fa-heart"></i>
                                                <span class="ml-1">{{$post->likes}}</span>
                                            </button>
                                        </form>
                                    @endif

                                </span>
                            </div>
                            <div class="row w-100 pb-0 mb-0 mt-2">
                                <small class="col-sm-6 text-muted">
                                    Created on : {{$post->created_at}}
                                </small>
                                <small class="col-sm-6 text-muted">
                                    Last updated : {{$post->updated_at}}
                                </small>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <a href="{{route('profile.show',['profile' => $post->user->id])}}" class="border-left row" style="border-radius:0px 5px 5px 0px ">
                                <div class="col-sm-5">
                                    <img src="{{asset('storage/profile_images/' . $post->user->profile->image)}}" class="rounded-circle my-2" style="object-fit: cover; width: 50px; height: 50px">
                                </div>
                                <div class="col-sm-7 align-items-center d-flex justify-content-center">
                                    <span style="font-size: 0.9em">{{ $post->user->profile->display_name }}</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <span>
                No posts found
            </span>
        @endforelse
        <div class="card">
            <div class="card-body">

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post/show.blade.php
@extends('adminLTE.master')

@section('content')
    <div class="container">
        <div class="content-header">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <a class="btn btn-primary" href="{{route('post.index')}}">
                        <i class="fa fa-arrow-left"></i>
                        <span class="ml-2">Back</span>
                    </a>
                </div>
{{--                <div class="col-sm-6">--}}
{{--                    <a class="btn btn-primary float-sm-right" href="#">--}}
{{--                        <i class="fa fa-plus"></i>--}}
{{--                        <span class="border-left m-2 p-2">--}}
{{--                            Add Comment--}}
{{--                        </span>--}}
{{--                    </a>--}}
{{--                </div>--}}
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-10">
                        <h2>{{$post->judul}}</h2>
                    </div>
                    <div class="col-sm-2">
                        @if($post->user->id == Auth::user()->id)
                            <div class="dropdown show float-right">
                                <a class="" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-ellipsis-v text-secondary"></i>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="{{route('post.edit',['post' => $post->id])}}">Edit</a>
                                    {{--                                        <a class="dropdown-item text-danger" href="#">Delete</a>--}}
                                    <form action="{{route('post.destroy',['post' => $post->id])}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" value="Delete" class="dropdown-item text-danger">
                                    </form>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
                <hr>
                @if($post->image != "noimage.jpg")
                    <div class="container-fluid d-flex justify-content-center">
                        <img src="{{asset('storage/post_images/' . $post->image)}}" style="max-width: 500px; max-height: 500px; object-fit: cover">
                    </div>
                @endif
                <p>{{$post->deskripsi}}</p>
            </div>
            <div class="card-footer py-1">
                <div class="row" >
                    <div class="col-sm-10" style="border-radius: 5px 0px 0px 5px">
                        <div class="w-100">
                            <span style="font-size: 1.4em">
                                @if($post->likes()->where('user_id',Auth::user()->id)->exists())
                                    <form action="{{route('likepost.destroy',['likepost' => $post->id])}}" method='post'>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-link btn-lg">
                                            <i class="fa fa-heart"></i>
                                            <span class="ml-1">{{$post->likes}}</span>
                                        </button>
                                    </form>
                                @else
                                    <form action="{{route('likepost.store')}}" method="POST">
                                        @csrf
                                        <input type="hidden" name="id" value="{{$post->id}}">
                                        <button type="submit" class="btn btn-link btn-lg">
                                            <i class="far fa-heart"></i>
                                            <span class="ml-1">{{$post->likes}}</span>
                                        </button>
                                    </form>

                                @endif
                            </span>
                        </div>
                        <div class="row w-100 pb-0 mb-0 mt-2">
                            <small class="col-sm-6 text-muted">
                                Created on : {{$post->created_at}}
                            </small>
                            <small class="col-sm-6 text-muted">
                                Last updated : {{$post->updated_at}}
                            </small>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <a href="{{route('profile.show',['profile' => $post->user->id])}}" class="border-left row" style="border-radius:0px 5px 5px 0px ">
                            <div class="col-sm-5">
                                <img src="{{asset('storage/profile_images/' . $post->user->profile->image)}}" class="rounded-circle my-2" style="object-fit: cover; width: 50px; height: 50px">
                            </div>
                            <div class="col-sm-7 align-items-center d-flex justify-content-center">
                                <span style="font-size: 0.9em">{{ $post->user->profile->display_name }}</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        @if(\Illuminate\Support\Facades\Route::currentRouteName() != 'comment.edit')
            <div class="card">
            <div class="card-body">
                <form action="{{route('post.comment.store',['post' => $post->id])}}" method="POST">
                    @csrf
                    <textarea class="form-control" rows="3" placeholder="Komentar" id="comment" name="text"></textarea>
                    <div class="container-fluid mt-2">
                        <button type="submit" class="btn btn-primary float-sm-right">
                            <i class="fa fa-plus"></i>
                            <span class="border-left m-2 p-2">
                                Add Comment
                            </span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
            @forelse($comments as $key => $comment)
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-10">
                                <h2>Re : {{$post->judul}}</h2>
                            </div>
                            <div class="col-sm-2">
                                @if($comment->user->id == Auth::user()->id)
                                    <div class="dropdown show float-right">
                                        <a class="" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-ellipsis-v text-secondary"></i>
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                            <a class="dropdown-item" href="{{route('comment.edit',['comment' => $comment->id])}}">Edit</a>
                                            {{--                                        <a class="dropdown-item text-danger" href="#">Delete</a>--}}
                                            <form action="{{route('comment.destroy',['comment' => $comment->id])}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <input type="submit" value="Delete" class="dropdown-item text-danger">
                                            </form>
                                        </div>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <hr>
                        <p>{{$comment->text}}</p>
                    </div>
                    <div class="card-footer py-1">
                        <div class="row" >
                            <div class="col-sm-10" style="border-radius: 5px 0px 0px 5px">
                                <div class="w-100">
                            <span style="font-size: 1.4em">
                                @if($comment->likes()->where('user_id',Auth::user()->id)->exists())
                                    <form action="{{route('likecomment.destroy',['likecomment' => $comment->id])}}" method='post'>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-link btn-lg">
                                            <i class="fa fa-heart"></i>
                                            <span class="ml-1">{{$comment->likes}}</span>
                                        </button>
                                    </form>
                                @else
                                    <form action="{{route('likecomment.store')}}" method="POST">
                                        @csrf
                                        <input type="hidden" name="id" value="{{$comment->id}}">
                                        <button type="submit" class="btn btn-link btn-lg">
                                            <i class="far fa-heart"></i>
                                            <span class="ml-1">{{$comment->likes}}</span>
                                        </button>
                                    </form>

                                @endif
                            </span>
                                </div>
                                <div class="row w-100 pb-0 mb-0 mt-2">
                                    <small class="col-sm-6 text-muted">
                                        Created on : {{$comment->created_at}}
                                    </small>
                                    <small class="col-sm-6 text-muted">
                                        Last updated : {{$comment->updated_at}}
                                    </small>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <a href="{{route('profile.show',['profile' => $comment->user->id])}}" class="border-left row" style="border-radius:0px 5px 5px 0px ">
                                    <div class="col-sm-5">
                                        <img src="{{asset('storage/profile_images/' . $comment->user->profile->image)}}" class="rounded-circle my-2" style="object-fit: cover; width: 50px; height: 50px">
                                    </div>
                                    <div class="col-sm-7 align-items-center d-flex justify-content-center">
                                        <span style="font-size: 0.9em">{{ $comment->user->profile->display_name }}</span>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            @empty

            @endforelse
        @else
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-10">
                            <h2>Re : {{$post->judul}}</h2>
                        </div>
                    </div>
                    <hr>
                    <form action="{{route('comment.update',['comment' => $comment->id])}}" method="POST">
                        @csrf
                        @method('PUT')
                        <textarea class="form-control" rows="3" placeholder="Komentar" id="comment" name="text">{{old('text',$comment->text)}}</textarea>
                        <div class="container-fluid mt-2">
                            <button type="submit" class="btn btn-primary float-sm-right">
                                <i class="fa fa-edit"></i>
                                <span class="border-left m-2 p-2">
                                Edit Comment
                            </span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        @endif
    </div>
@endsection