routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'PostController@index')->name('home');
Route::resource('post','PostController');
Route::resource('profile','ProfileController');
Route::resource('likepost','LikePostController')->only([
    'store','destroy'
]);
Route::resource('likecomment','LikeCommentController')->only([
    'store','destroy'
]);
Route::resource('post.comment','CommentController')->shallow();

Route::post('/follow','UserController@followUser')->name('follow');
Route::delete('/unfollow','UserController@unfollowUser')->name('unfollow');

resources/views/editProfile.blade.php
@extends('adminlte.master')

@section('content')
    <div class="container">
        <div class="content-header">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <a class="btn btn-primary" href="{{route('profile.show',['profile' => $profile->id])}}">
                        <i class="fa fa-arrow-left"></i>
                        <span class="ml-2">Back</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="card ">
            <div class="card-header">
                <h3 class="card-title">Edit Profile</h3>
            </div>
            <form action="{{ route('profile.update',['profile' => $profile->id])}}" method="POST" enctype="multipart/form-data">
                <div class="card-body">
                    @csrf
                    @method('put')

                    <div class="form-group row mt-1">
                        <label for="profile_image" class="col-md-2 col-form-label">{{ __('Profile Photo') }}</label>
                        <div class="col-md-6">
                            <input type="file" class="form-control-sm" id="profile_image" name="image" value="{{old('image','')}}" placeholder="Enter Image">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="display_name">Display Name</label>
                        <input type="text" class="form-control" name="display_name" id="display_name" value="{{ old('display_name',$profile->display_name) }}" placeholder="Masukkan Nama Lengkap">
                        @error('display_name')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="bio">Biodata</label>
                        <input type="text" class="form-control" name="bio" id="bio" value="{{ old('bio',$profile->bio) }}" placeholder="Masukkan Bio">
                        @error('bio')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Edit Profile</button>

                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('adminLTE.master')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <a class="btn btn-primary" href="{{route('post.index')}}">
                    <i class="fa fa-arrow-left"></i>
                    <span class="ml-2">Back</span>
                </a>
            </div>
            <div class="col-sm-6">
                @if(Auth::user()->id == $profile->user->id)
                    <a href="{{ route('profile.edit',['profile'=>Auth::user()->profile->id]) }}" class="btn fas fa-edit btn-outline-primary mb-3 float-sm-right">Edit Profile</a>
                @endif
            </div>
        </div>
    </div>
</div>
<div class="row d-flex justify-content-center">

    <div class="card "   style="width: 50%;">

        <div class="card-body ">
            <div class="image d-flex justify-content-center">
                <img src="{{asset('storage/profile_images/' . $profile->image)}}" class="img-circle elevation-1" width="300" height="300" alt="User Image">
            </div>
            <div class="">
                <h5 class=""><b>Name :</b></h5>
                <p class="card-text">{{ $profile->display_name }}</p>
            </div>
            <hr>
            <div class="">
                <h5 class=""><b>Biodata :</b></h5>
                <p class="card-text">{{ $profile->bio }}</p>
            </div>
            <hr>
            <div class="row my-2">
                <div class="col-md-6 text-center border-right">
                    <div>
                        <span class="font-weight-bold">Following</span>
                    </div>
                    <div>
                        <span class="text-primary font-weight-bold">{{$profile->following}}</span>
                    </div>
                </div>
                <div class="col-md-6 text-center">
                    <div>
                        <span class="font-weight-bold">Followers</span>
                    </div>
                    <div>
                        <span class="text-primary font-weight-bold">{{$profile->followers}}</span>
                    </div>
                </div>
            </div>
            @if(Auth::user()->id != $profile->user->id)


                    @if(Auth::user()->follow()->where('followed_user_id', $profile->user->id)->exists())
                        <form action="{{route('unfollow')}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <hr>
                            <input type="hidden" name="id" value="{{$profile->user->id}}">
                            <div class="container-fluid">
                                <button type="submit" class="btn btn-danger btn-lg btn-block">Unfollow</button>
                            </div>
                        </form>
                    @else
                        <form action="{{route('follow')}}" method="POST">
                            @csrf
                            <hr>
                            <input type="hidden" name="id" value="{{$profile->user->id}}">
                            <div class="container-fluid">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Follow</button>
                            </div>
                        </form>
                    @endif

            @endif
        </div>
    </div>
</div>


<span style="display: inline;">

</span>

@endsection